services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: "${PUID}:${PGID}"
    ports:
      - "${ND_PORT}:4533"
    environment:
      TZ: "${TZ}"
      ND_SCANNER_SCHEDULE: "${ND_SCANNER_SCHEDULE}"
      ND_SCANNER_IGNOREDOTFOLDERS: "${ND_SCANNER_IGNOREDOTFOLDERS}"
      ND_LOGLEVEL: "${ND_LOGLEVEL}"
      ND_SESSIONTIMEOUT: "${ND_SESSIONTIMEOUT}"
      ND_BASEURL: "${ND_BASEURL}"
      ND_PLUGINS_ENABLED: "${ND_PLUGINS_ENABLED}"
      ND_PLUGINS_AUTORELOAD: "${ND_PLUGINS_AUTORELOAD}"
      ND_BACKUP_PATH: "/data/backup"
      ND_BACKUP_SCHEDULE: "${ND_BACKUP_SCHEDULE}"
      ND_BACKUP_COUNT: "${ND_BACKUP_COUNT}"
    volumes:
      - ./data:/data
      - ${MUSIC_DIR}:/music:ro
    restart: unless-stopped

  nfs-server:
    image: itsthenetwork/nfs-server-alpine:latest
    container_name: nfs-music
    privileged: true               # requerido: NFS necesita acceso a módulos del kernel del host
    environment:
      SHARED_DIRECTORY: /music
      READ_ONLY: "${NFS_READ_ONLY}"
      SYNC: "${NFS_SYNC}"
      PERMITTED: "${NFS_PERMITTED}"
    volumes:
      - ${MUSIC_DIR}:/music:ro
    ports:
      - "${NFS_PORT}:2049"
    restart: unless-stopped

  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    environment:
      TZ: "${TZ}"
    ports:
      - "${NPM_HTTP_PORT}:80"      # HTTP — necesario para el reto ACME/Let's Encrypt
      - "${NPM_HTTPS_PORT}:443"    # HTTPS
      - "${NPM_ADMIN_PORT}:81"     # panel de administración web de NPM
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    restart: unless-stopped

  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
      SUBDOMAINS: "${DUCKDNS_SUBDOMAINS}"
      TOKEN: "${DUCKDNS_TOKEN}"
      LOG_FILE: "${DUCKDNS_LOG_FILE}"
    volumes:
      - ./duckdns/config:/config
    restart: unless-stopped
